# The name of our workflow
name: Test
on:
  push:
env:
  AMI : "ami-0acf3d8ed5bf3ec9d" # msitest-agent-windows-server-2022-1
  AWS_REGION : "eu-west-1"
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkoutjobs:
jobs:
  AWSTest:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::217307881341:role/GitHubActions
          role-session-name: githubactions
          aws-region: ${{ env.AWS_REGION }}
      - name: Clone openvpn-windows-test repo
        uses: actions/checkout@v3
        with:
          repository: lstipakov/openvpn-windows-test
          ref: tclient_aws
          path: openvpn-windows-test
        
      - name: fetch MSI from build workflow
        working-directory: test
        shell: pwsh
        run: Invoke-WebRequest https://build.openvpn.net/downloads/snapshots/github-actions/openvpn2/openvpn-master-20221111T0935-199081c2-amd64.msi -OutFile OpenVPN-2.6git-amd64.msi
      
      - name: Run AWS test
        working-directory: test
        shell: pwsh
        run: .\Start-AWSTest.ps1
